### ISSUE TITLE
Prometheus remote write not working

### ISSUE THREAD

**Issue by importhuman** [pree-dew/timeseries_golem#3]
I have the following `exporter_config.json`:

```json
{
	"exporter": "prometheus",
	"metric_export_mode": "remote_write",
	"pickup_duration": 10,
	"remote_write": {
		"endpoint": "<write-endpoint>"
	}
}
```

But this is still logging output to console, and there are no metrics being sent to the write endpoint.

Looks related to the `reader` in `exporter_utils.py`, can take this up

**Comment by pree-dew** [comment]
Multiple issues noticed:
1. `reader` was not initialised for prometheus exporter
2.  Only 1 `reader` should be created while setting provider because as soon as we initialise a `reader` it's `collect` method start working and on new initialise of `reader` it creates a new one instead of overriding. Since only one of them is registered with `MeterProvider` the other one will keep raising the error.

**Solution**
Initialise reader only once.

**Comment by pree-dew** [comment]
PR for the same https://github.com/pree-dew/timeseries_golem/pulls

**Comment by pree-dew** [comment]
Merged.
